// <auto-generated/>
namespace SteganographyNotepad.Views;

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

public partial class CoverImageSettingsView : UserControl
{
    public CoverImageSettingsView()
    {
        InitializeComponent();
    }
}