// <auto-generated/>
namespace SteganographyNotepad.Views;

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

public partial class SettingsView : UserControl
{
    public SettingsView()
    {
        InitializeComponent();
    }
}