// <auto-generated/>
#pragma warning disable CS1591
namespace SteganographyNotepad.Views;

using Avalonia.Controls;

public partial class CleanView : UserControl
{
    public CleanView()
    {
        InitializeComponent();
    }
}